/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DIconAddCondition: typeof import('./src/icons/svg/add-condition.vue')['default']
    DIconAppGithub: typeof import('./src/icons/svg/app-github.vue')['default']
    DIconApplication: typeof import('./src/icons/svg/application.vue')['default']
    DIconDbExport: typeof import('./src/icons/svg/db-export.vue')['default']
    DIconDbImport: typeof import('./src/icons/svg/db-import.vue')['default']
    DIconNotify: typeof import('./src/icons/svg/notify.vue')['default']
    DIconReset: typeof import('./src/icons/svg/reset.vue')['default']
    DIconSetting: typeof import('./src/icons/svg/setting.vue')['default']
    DIconSizer: typeof import('./src/icons/svg/sizer.vue')['default']
    DIconSort: typeof import('./src/icons/svg/sort.vue')['default']
    DIconTable: typeof import('./src/icons/svg/table.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAutoResizer: typeof import('element-plus/es')['ElAutoResizer']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTableV2: typeof import('element-plus/es')['ElTableV2']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElTree: typeof import('element-plus/es')['ElTree']
    IconCirclePlus: typeof import('@element-plus/icons-vue')['CirclePlus']
    IconCloseBold: typeof import('@element-plus/icons-vue')['CloseBold']
    IconDelete: typeof import('@element-plus/icons-vue')['Delete']
    IconEditPen: typeof import('@element-plus/icons-vue')['EditPen']
    IconFolderOpened: typeof import('@element-plus/icons-vue')['FolderOpened']
    IconPlus: typeof import('@element-plus/icons-vue')['Plus']
    IconRefreshRight: typeof import('@element-plus/icons-vue')['RefreshRight']
    IconSearch: typeof import('@element-plus/icons-vue')['Search']
    IconSelect: typeof import('@element-plus/icons-vue')['Select']
    IconSemiSelect: typeof import('@element-plus/icons-vue')['SemiSelect']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
