/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DIconAppGithub: typeof import('./src/icons/svg/app-github.vue')['default']
    DIconApplication: typeof import('./src/icons/svg/application.vue')['default']
    DIconNotify: typeof import('./src/icons/svg/notify.vue')['default']
    DIconSetting: typeof import('./src/icons/svg/setting.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
